# Generated by Django 3.1.4 on 2020-12-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece'), ('dozen', 'dozen'), ('gross', 'gross'), ('half gross', 'half gross'), ('Kg', 'Kg'), ('packet', 'packet')], default='piece', max_length=21),
        ),
    ]
