# Generated by Django 5.0.1 on 2024-07-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_manager_emp_id',
            new_name='store_manager_username',
        ),
    ]
