# Generated by Django 5.0.1 on 2024-07-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores_app', '0002_rename_store_manager_emp_id_store_store_manager_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_emp',
            name='store_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores_app.store'),
        ),
    ]
