# Generated by Django 5.0.1 on 2024-08-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=81)),
                ('addr', models.CharField(max_length=80)),
                ('visit_freq', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('store_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores_app.store')),
            ],
        ),
        migrations.CreateModel(
            name='bill_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores_app.store')),
                ('cust_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=81)),
                ('price', models.IntegerField()),
                ('WS_price', models.IntegerField(blank=True, default=121, null=True)),
                ('unit', models.CharField(choices=[('piece', 'piece'), ('dozen', 'dozen'), ('gross', 'gross'), ('half gross', 'half gross'), ('Kg', 'Kg'), ('packet', 'packet'), ('set', 'set')], default='piece', max_length=21)),
                ('tags', models.CharField(help_text='A list of comma seperated tags', max_length=150)),
                ('available_qty', models.IntegerField(default=0)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores_app.store')),
            ],
        ),
    ]
