# Generated by Django 3.1.4 on 2021-01-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210102_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_data',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill_data',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
