# Generated by Django 5.0.1 on 2024-07-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210103_2059'),
        ('stores_app', '0004_remove_store_store_manager_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_data',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores_app.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='WS_price',
            field=models.IntegerField(blank=True, default=121, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores_app.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece'), ('dozen', 'dozen'), ('gross', 'gross'), ('half gross', 'half gross'), ('Kg', 'Kg'), ('packet', 'packet'), ('set', 'set')], default='piece', max_length=21),
        ),
    ]
