# Generated by Django 5.0.1 on 2024-08-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_bill_data_store_product_ws_price_product_store_and_more'),
        ('stores_app', '0004_remove_store_store_manager_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=81)),
                ('addr', models.CharField(max_length=80)),
                ('visit_freq', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('store_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores_app.store')),
            ],
        ),
    ]
