# Generated by Django 5.0.1 on 2024-08-17 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_data',
            name='cust_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer'),
        ),
    ]
