# Generated by Django 3.1.4 on 2020-12-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bill',
            new_name='bill_data',
        ),
    ]
