# Generated by Django 3.1.4 on 2020-12-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_bill_data2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_data2',
            name='b',
            field=models.CharField(max_length=5000),
        ),
    ]
