# Generated by Django 3.1.4 on 2020-12-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201217_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bill_data',
        ),
    ]
