# Generated by Django 3.1.4 on 2020-12-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_bill_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bill_data2',
            new_name='bill_data',
        ),
    ]
