# Generated by Django 3.1.4 on 2021-01-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201217_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_data',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bill_data',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
